import type {
  NormalizedTransaction,
  PnLReport,
  QboAccount,
} from "@/lib/qbo/types";

export function getDemoAccounts(): QboAccount[] {
  return [
    {
      Id: "1",
      Name: "Advertising",
      AccountType: "Expense",
      Classification: "Expense",
      Active: true,
    },
    {
      Id: "2",
      Name: "Office Supplies",
      AccountType: "Expense",
      Classification: "Expense",
      Active: true,
    },
    {
      Id: "3",
      Name: "Travel",
      AccountType: "Expense",
      Classification: "Expense",
      Active: true,
    },
    {
      Id: "4",
      Name: "Meals and Entertainment",
      AccountType: "Expense",
      Classification: "Expense",
      Active: true,
    },
    {
      Id: "5",
      Name: "Software Subscriptions",
      AccountType: "Expense",
      Classification: "Expense",
      Active: true,
    },
    {
      Id: "6",
      Name: "Utilities",
      AccountType: "Expense",
      Classification: "Expense",
      Active: true,
    },
    {
      Id: "7",
      Name: "Sales",
      AccountType: "Income",
      Classification: "Revenue",
      Active: true,
    },
    {
      Id: "8",
      Name: "Uncategorized Expense",
      AccountType: "Expense",
      Classification: "Expense",
      Active: true,
    },
    {
      Id: "9",
      Name: "Uncategorized Income",
      AccountType: "Income",
      Classification: "Revenue",
      Active: true,
    },
  ];
}

export function getDemoTransactions(): NormalizedTransaction[] {
  return [
    {
      id: "d1",
      syncToken: "0",
      source: "Demo",
      date: "2026-07-18",
      amount: -84.22,
      description: "STARBUCKS STORE 10221",
      vendorName: "Starbucks",
      currentAccountId: "8",
      currentAccountName: "Uncategorized Expense",
      isUncategorized: true,
    },
    {
      id: "d2",
      syncToken: "0",
      source: "Demo",
      date: "2026-07-16",
      amount: -29.99,
      description: "ADOBE *CREATIVE CLOUD",
      vendorName: "Adobe",
      currentAccountId: "8",
      currentAccountName: "Uncategorized Expense",
      isUncategorized: true,
    },
    {
      id: "d3",
      syncToken: "0",
      source: "Demo",
      date: "2026-07-14",
      amount: -212.4,
      description: "DELTA AIR LINES",
      vendorName: "Delta",
      currentAccountId: "8",
      currentAccountName: "Uncategorized Expense",
      isUncategorized: true,
    },
    {
      id: "d4",
      syncToken: "0",
      source: "Demo",
      date: "2026-07-12",
      amount: -56.18,
      description: "OFFICE DEPOT #441",
      vendorName: "Office Depot",
      currentAccountId: "8",
      currentAccountName: "Uncategorized Expense",
      isUncategorized: true,
    },
    {
      id: "d5",
      syncToken: "0",
      source: "Demo",
      date: "2026-07-10",
      amount: -450.0,
      description: "FACEBOOK ADS",
      vendorName: "Meta",
      currentAccountId: "8",
      currentAccountName: "Uncategorized Expense",
      isUncategorized: true,
    },
    {
      id: "d6",
      syncToken: "0",
      source: "Demo",
      date: "2026-07-08",
      amount: 3200.0,
      description: "ACME CLIENT PAYMENT",
      vendorName: "Acme Corp",
      currentAccountId: "9",
      currentAccountName: "Uncategorized Income",
      isUncategorized: true,
    },
    {
      id: "d7",
      syncToken: "0",
      source: "Demo",
      date: "2026-07-05",
      amount: -118.33,
      description: "CITY POWER & LIGHT",
      vendorName: "City Power",
      currentAccountId: "6",
      currentAccountName: "Utilities",
      isUncategorized: false,
    },
  ];
}

export function getDemoPnL(startDate: string, endDate: string): PnLReport {
  return {
    startDate,
    endDate,
    title: "Profit and Loss",
    currency: "USD",
    incomeTotal: 18450,
    expenseTotal: 11240.55,
    netIncome: 7209.45,
    rows: [
      { label: "Income", amount: 18450, depth: 0, group: "Income" },
      { label: "Sales", amount: 15200, depth: 1, group: "Income" },
      { label: "Services", amount: 3250, depth: 1, group: "Income" },
      { label: "Total Income", amount: 18450, depth: 0, group: "Income" },
      { label: "Expenses", amount: 11240.55, depth: 0, group: "Expenses" },
      { label: "Advertising", amount: 2100, depth: 1, group: "Expenses" },
      {
        label: "Software Subscriptions",
        amount: 890.4,
        depth: 1,
        group: "Expenses",
      },
      { label: "Travel", amount: 1640.15, depth: 1, group: "Expenses" },
      { label: "Office Supplies", amount: 420, depth: 1, group: "Expenses" },
      {
        label: "Meals and Entertainment",
        amount: 610,
        depth: 1,
        group: "Expenses",
      },
      { label: "Utilities", amount: 480, depth: 1, group: "Expenses" },
      { label: "Contractors", amount: 5100, depth: 1, group: "Expenses" },
      { label: "Total Expenses", amount: 11240.55, depth: 0, group: "Expenses" },
      { label: "Net Income", amount: 7209.45, depth: 0, group: "Net" },
    ],
  };
}
